// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4fWCx-rPjP2ObWb_xHQv5KCxJNc-APnc',
    appId: '1:886788013556:web:4111ed7c56a594d7b90da1',
    messagingSenderId: '886788013556',
    projectId: 'fir-auth-app-568b7',
    authDomain: 'fir-auth-app-568b7.firebaseapp.com',
    storageBucket: 'fir-auth-app-568b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6UmiyEk3y41GBkp8R57kCSZD1t6EQD0',
    appId: '1:886788013556:android:8bcf87fcb7f4a27fb90da1',
    messagingSenderId: '886788013556',
    projectId: 'fir-auth-app-568b7',
    storageBucket: 'fir-auth-app-568b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsM0AM0LuXgCoWL0bn94wNVHxQD-9UM3s',
    appId: '1:886788013556:ios:2a25cd73f55ea845b90da1',
    messagingSenderId: '886788013556',
    projectId: 'fir-auth-app-568b7',
    storageBucket: 'fir-auth-app-568b7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsM0AM0LuXgCoWL0bn94wNVHxQD-9UM3s',
    appId: '1:886788013556:ios:2a25cd73f55ea845b90da1',
    messagingSenderId: '886788013556',
    projectId: 'fir-auth-app-568b7',
    storageBucket: 'fir-auth-app-568b7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4fWCx-rPjP2ObWb_xHQv5KCxJNc-APnc',
    appId: '1:886788013556:web:ad7116d899970ac6b90da1',
    messagingSenderId: '886788013556',
    projectId: 'fir-auth-app-568b7',
    authDomain: 'fir-auth-app-568b7.firebaseapp.com',
    storageBucket: 'fir-auth-app-568b7.firebasestorage.app',
  );
}
